### ISSUE TITLE
Close game the user opened

### ISSUE THREAD

**Issue by nalcholina** [nalch/continuum#19]
It seems that it is impossible to close a game that I've opened and it will stay in the games list.

**Comment by nalch** [comment]
It's kind of the idea not to have too much settings and options, so i refrain from having an ownerspecific option panel or the like.

I believe the way to go is a cronjob, that deletes untouched games after a specified period of time (not sure, how long this would be as I like the idea of a letterchess style continuum game).

**Comment by nalch** [comment]
Use http://mongoosejs.com/docs/guide.html#timestamps to save updates and test for age

**Comment by nalch** [comment]
This should be ready, but has to be tested. First testcases reside under `test/gameCleanup.js`.
There should be tests, that only games, that are more than five days old, are set to finished, but these are.
