### ISSUE TITLE
Username can just change equal in a local game

### ISSUE THREAD

**Issue by nalcholina** [nalch/continuum#28]
Follow these steps
1. Start a game
2. Click "Play against a local player"
3. Change Username of the the Owner or the Opponent
Result: The username change for the Owner AND the Opponent
Expected: Possible to change the username only for one of the players

FF 47.0, no cookies allowed

**Comment by nalch** [comment]
The way it is now, there is only one player. The owner is simultaneously the opponent. So there is no way to only change one of the nicknames.
This is deeply rooted in the computation of which player's turn it is and so not easily changed. It simply was implemented in order not to have to open the incognito mode every time something should be tested.

This will be a task in the future, when other players (like bots) are incorporated.
