### ISSUE TITLE
Owner can play without an opponent

### ISSUE THREAD

**Issue by nalcholina** [nalch/continuum#30]
Follow these steps:
1. Create a game.
2. A visitor join the game.
3. The game is startet with the visitor.
4. The visitor leaves the game before the first move was made.
Result: It is possible for the Owner (who left there alone) to make a move.

I am not sure what is expected?

I guess it will work in both directions

**Comment by nalch** [comment]
There is no way to leave a game. You can always close the page and come back later to continue the game. Maybe there should be timeout after that the game is considered lost. This should be implemented in #19.
